"""
create_placeholders.py
-----------------------
Creates stub index.md files for each module so MkDocs can build
without running the full NotebookLM expansion first.

Run:
    python scripts/create_placeholders.py
"""

import os

MODULES = [
    (1, "foundations-of-islamic-finance", "Foundations of Islamic Finance",
     "Core philosophy, three prohibitions (Riba, Gharar, Maysir), positive structuring principles, asset linkage, and practical commercial application."),
    (2, "islamic-finance-vs-conventional-finance", "Islamic Finance vs Conventional Finance",
     "Common misconceptions, side-by-side comparison, economic substance vs legal form, and where Islamic finance is strong or contested."),
    (3, "core-islamic-contracts-and-structuring-toolkit", "Core Islamic Contracts and Structuring Toolkit",
     "Complete contract family map: Murabaha, Tawarruq, Ijara, Musharaka, Mudaraba, Salam, Istisna, Wakala, Sukuk, and modern structuring tools."),
    (4, "shariah-governance-and-institutional-framework", "Shariah Governance and Institutional Framework",
     "Multi-tier governance model, AAOIFI, IFSB, IIFM, jurisdictional divergence, scholar concentration risks, and the fatwa process."),
    (5, "islamic-banking-treasury-and-liquidity", "Islamic Banking, Treasury, and Liquidity",
     "Balance sheet structure, PSIA, core application areas, treasury and liquidity management, and family office relevance."),
    (6, "sukuk-and-public-capital-markets", "Sukuk and Public Capital Markets",
     "Sukuk definition, asset-based vs asset-backed, structure menu, secondary market issues, equity screening, Islamic REITs, and ESG sukuk."),
    (7, "islamic-finance-in-private-markets", "Islamic Finance in Private Markets",
     "Why private markets suit Islamic finance, fund structuring, the halal waterfall, leverage challenge, private credit, infrastructure, and restructurings."),
    (8, "case-study-compendium", "Case Study Compendium",
     "Ten in-depth case studies: UK Sovereign Sukuk, UAE Treasury, Saudi PIF, ADNOC, Green Sukuk (Malaysia, Indonesia, UAE), Dana Gas restructuring."),
    (9, "market-landscape-and-ecosystem", "Market Landscape and Ecosystem",
     "Global market size (USD 3.88–5.98 trillion), three major hubs (Malaysia, Saudi Arabia, UAE), and key ecosystem players."),
    (10, "new-developments-innovation-and-debate", "New Developments, Innovation, and Debate",
     "Form vs substance debate, AAOIFI Standard 62, tokenisation, ESG convergence, AI-driven compliance, and the authenticity movement."),
    (11, "product-development-and-opportunity-mapping", "Product Development and Opportunity Mapping",
     "White space map across six opportunity categories and decision matrix for platform launch."),
    (12, "executive-toolkit", "Executive Toolkit",
     "Five-question robustness test, robustness checklist, red flags, due-diligence questions, Islamic PE evaluation, and platform decision framework."),
]

TEMPLATE = """---
title: "Module {num}: {title}"
description: "{description}"
---

# Module {num}: {title}

> **Note:** Full content for this module is generated by running `python scripts/expand_sections.py`.
> The sections below are stubs — run the expansion script to populate them with NotebookLM-sourced content.

{description}

---

## Sections

{section_list}

---

<div class="executive-refresher">
<h3>Executive Refresher</h3>

- This module will be fully expanded with sourced content from the NotebookLM notebook.
- Run `python scripts/expand_sections.py` to populate.
- Then run `python scripts/generate_quizzes.py` to inject the Knowledge Check Quiz.
</div>

<div class="quiz-section">
<h3>Knowledge Check Quiz</h3>

*Quiz questions will appear here after running `generate_quizzes.py`.*
</div>
"""

SECTION_LISTS = {
    1: ["1.1 Core Philosophy and Operating Principles", "1.2 The Three Core Prohibitions",
        "1.3 Positive Structuring Principles", "1.4 Asset Linkage and Commercial Legitimacy",
        "1.5 Practical Commercial Application", "1.6 Risks and Limitations"],
    2: ["2.1 Common Misconceptions", "2.2 Side-by-Side Comparison",
        "2.3 Economic Substance vs Legal Form", "2.4 Where Islamic Finance Is Strong vs Contested"],
    3: ["3.1 Contract Family Map", "3.2 Murabaha (Cost-Plus Sale)",
        "3.3 Tawarruq / Commodity Murabaha", "3.4 Ijara and Ijara Muntahia Bittamleek",
        "3.5 Musharaka and Diminishing Musharaka", "3.6 Mudaraba (Profit-Sharing Partnership)",
        "3.7 Salam and Istisna", "3.8 Wakala, Kafala, and Qard Hasan",
        "3.9 Wa'ad, SPVs, and Modern Structuring Tools", "3.10 Contract Application Matrix"],
    4: ["4.1 The Multi-Tier Governance Model", "4.2 AAOIFI and IFSB: The Global Standard Setters",
        "4.3 Jurisdictional Divergence", "4.4 Scholar Concentration and Governance Risks",
        "4.5 Standardisation vs Innovation", "4.6 The Fatwa Process"],
    5: ["5.1 Balance Sheet Structure", "5.2 Core Application Areas",
        "5.3 Treasury and Liquidity Management", "5.4 Family Office Relevance"],
    6: ["6.1 Sukuk Definition and Economic Role", "6.2 Asset-Based vs Asset-Backed: The Critical Distinction",
        "6.3 Sukuk Structure Menu", "6.4 Secondary Market Issues",
        "6.5 Equity Screening and Listed Products", "6.6 Islamic REITs and ETFs",
        "6.7 ESG and Sustainable Sukuk"],
    7: ["7.1 Why Private Markets Are the Natural Home", "7.2 Structuring the Fund: GP/LP Dynamics",
        "7.3 The 'Halal Waterfall' and Carry Mechanics", "7.4 The Leverage Challenge",
        "7.5 Private Credit and Acquisition Finance", "7.6 Infrastructure and Real Estate",
        "7.7 Restructurings and Special Situations"],
    8: ["8.1 UK Sovereign Sukuk (Ijara, 2014)", "8.2 UAE Treasury Sukuk Programme",
        "8.3 Saudi PIF International Sukuk Programme", "8.4 ADNOC Murban Debut Sukuk (2025)",
        "8.5 Tadau Energy Green Sukuk (Malaysia, 2017)",
        "8.6 Republic of Indonesia Sovereign Green Sukuk (2018)",
        "8.7 Majid Al Futtaim Corporate Green Sukuk (UAE, 2019)",
        "8.8 Malaysia SRI Sukuk Ecosystem", "8.9 Emirates Islamic EmFIN Platform",
        "8.10 Dana Gas Sukuk Restructuring (2017-2018)"],
    9: ["9.1 Global Market Size", "9.2 The Three Major Hubs", "9.3 Key Ecosystem Players"],
    10: ["10.1 Form vs Substance (Still Central)", "10.2 AAOIFI Standard 62 and Standardisation Pressure",
         "10.3 Digitisation and Tokenisation", "10.4 ESG and Sustainable Sukuk Convergence",
         "10.5 AI-Driven Shariah Compliance", "10.6 The Authenticity Movement",
         "10.7 Private Market Innovation"],
    11: ["11.1 White Space Map", "11.2 Decision Matrix for Platform Launch"],
    12: ["12.1 The Five-Question Robustness Test", "12.2 Checklist for Structure Robustness",
         "12.3 Red Flags", "12.4 Questions to Ask Key Parties",
         "12.5 Evaluating an Islamic PE Opportunity", "12.6 Platform Decision Framework"],
}


def main():
    for num, slug, title, description in MODULES:
        module_dir = f"docs/module-{str(num).zfill(2)}-{slug}"
        os.makedirs(module_dir, exist_ok=True)
        filepath = os.path.join(module_dir, "index.md")

        sections = SECTION_LISTS.get(num, [])
        section_list = "\n".join(f"- {s}" for s in sections)

        content = TEMPLATE.format(
            num=num,
            title=title,
            description=description,
            section_list=section_list,
        )

        with open(filepath, "w", encoding="utf-8") as f:
            f.write(content)

        print(f"Created: {filepath}")

    print("\nAll placeholder files created.")


if __name__ == "__main__":
    main()
